feat: add non atomic action interpeter agent
ostis-ai/ostis-ps-lib pull request #2
Opened 2024-03-28 17:29 UTC by ProtasSemyon

2024-04-02 08:28 UTC, kilativ-dotcom requested changes

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/agent/NonAtomicActionInterpreterAgent.cpp
> +  catch (std::exception & ex)
please replace std errors with sc exceptions

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/agent/NonAtomicActionInterpreterAgent.cpp
> +    SC_LOG_DEBUG(exception.Description() << "\nNonAtomicActionInterpreterAgent finished with errors");
```suggestion
    SC_LOG_Error(exception.Description());
    SC_LOG_DEBUG("NonAtomicActionInterpreterAgent finished with errors");
```

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/agent/NonAtomicActionInterpreterAgent.cpp
> +  catch (std::exception & ex)
in all files

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/utils/TemplateParamsUtils.cpp
> +    templateParams.Add(variableIdentifier, variableReplacementPair.second);
```suggestion
    templateParams.Add(variableReplacementPair.first, variableReplacementPair.second);
```
now sc-machine allows to add template param by var
maybe system idtf map can be deleted, can you try and get rid of it?

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/interpreter/NonAtomicActionInterpreter.cpp
> +  ScAddrVector orderedTransitionCandidates;
```suggestion
  ScAddrList orderedTransitionCandidates;
```
this collection is used for push_back, search and iteration, there is no access by index so it'll be better to use list

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/interpreter/NonAtomicActionInterpreter.cpp
> +  context->HelperSearchTemplate(scTemplate, searchResult);
this is an only place in this file that uses template search, how about replace it with Iterator5 or IteratorUtils?

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/interpreter/NonAtomicActionInterpreter.cpp
> +    LogicFormulaManager logicFormulaSearcher(context);
this manager better be initialized only once in interpreter's constructor as unique_ptr
now it is created and deleted for every condition check

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/manager/LogicFormulaManager.cpp
> +// TODO: reuse inference module logic for formulas check
```suggestion
```
now there is no access to inferece module

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/test/agent/AssignDynamicArgumentTestAgent.hpp
> +}  // namespace commonTest
```suggestion
}  // namespace wrong namespace, and in other agents also wrong namespace
```

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/test/tests.cmake
> +add_definitions(-DCOMMON_MODULE_TEST_SRC_PATH="${CMAKE_CURRENT_LIST_DIR}")
```suggestion
add_definitions(-D something about interpreter _TEST_SRC_PATH="${CMAKE_CURRENT_LIST_DIR}")
```
you removed all mentions of common module, replace this as well

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/test/tests.cmake
> +    INCLUDES ${SC_MEMORY_SRC}/tests/sc-memory/_test ${SC_COMMON_MODULE_SRC} ${SC_MACHINE_PATH}/sc-tools/sc-builder/src)
```suggestion
    INCLUDES ${SC_MEMORY_SRC}/tests/sc-memory/_test ${SC_ looks like this one also should be about interpreter, and its name should match one used in cxx/CMakeLists.txt _MODULE_SRC} ${SC_MACHINE_PATH}/sc-tools/sc-builder/src)
```

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/utils/ActionUtils.hpp
> +using namespace std;
please remove this using

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/utils/RelationUtils.cpp
> +    ScMemoryContext * ms_context,
```suggestion
    ScMemoryContext * context,
```

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/utils/RelationUtils.cpp
> +ScAddr RelationUtils::setOutValue(
maybe this is unused

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/utils/RelationUtils.cpp
> +ScAddr RelationUtils::setInValue(
maybe unused

2024-04-02 08:28 UTC, kilativ-dotcom commented on .gitignore
> +.DS_Store
add newline

2024-04-02 08:28 UTC, kilativ-dotcom commented on CMakeLists.txt
> +add_subdirectory(cxx)
newline

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/.gitignore
> +**/generated
newline

2024-04-02 08:28 UTC, kilativ-dotcom commented on cxx/CMakeLists.txt
> +add_subdirectory(non-atomic-action-interpreter-module)
newline

2024-04-02 08:28 UTC, kilativ-dotcom commented on docker-compose.yml
> +    driver: bridge
newline

2024-04-02 08:28 UTC, kilativ-dotcom commented on docs/software_components/agents/images/init_action_agent_input.png
this agent wasn't added

2024-04-02 08:28 UTC, kilativ-dotcom commented on docs/software_components/agents/images/non_atomic_action_interpretation_agent_example.png
I thought there should be an edge between template and _compound_action_message_... with rrel_key_sc_element relation

2024-04-02 08:28 UTC, kilativ-dotcom commented on docs/software_components/agents/images/non_atomic_action_interpretation_agent_example.png
other files have `program` identifier for this program, maybe rename program in this file?

2024-04-02 08:28 UTC, kilativ-dotcom commented on docs/software_components/agents/images/wait_return_set_agent_input.png
this agent wasn't added

2024-04-02 08:28 UTC, kilativ-dotcom commented on docs/software_components/agents/non_atomic_action_interpretation_agent.md
> +Is an agent that generates an action description in the knowlendge base based on the template (program) received. If there are sets of arguments then it performs a role mapping before generation.
```suggestion
This is an agent that generates an action description in the knowlendge base based on the template (program) received. If there are sets of arguments then it performs a role mapping before generation.
```

2024-04-02 08:28 UTC, kilativ-dotcom commented on mkdocs.yml
> +  - pymdownx.superfences
newline

2024-04-13 07:32 UTC, kilativ-dotcom requested changes

2024-04-13 07:32 UTC, kilativ-dotcom commented on cxx/CMakeLists.txt
> +add_subdirectory(common-module)
add newline

2024-04-13 07:32 UTC, kilativ-dotcom commented on cxx/common-module/utils/RelationUtils.hpp
> +};
these two aren't in cpp

2024-04-13 07:32 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/agent/NonAtomicActionInterpreterAgent.cpp
> +  catch (utils::ExceptionCritical & ex)
looks like try blocks can be merged in one and catch statement can catch utils::ScException
@NikiforovSergei does return code(ERROR or ERROR_INVALID_PARAMS) matters or it can be ERROR in any case?

2024-04-13 07:32 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/interpreter/NonAtomicActionInterpreter.cpp
> +          "NonAtomicActionInterpreter: the processing action of the current message has been interrupted.");
```suggestion
          "NonAtomicActionInterpreter: the processing action of the current non-atomic action has been interrupted.");
```

2024-04-13 07:32 UTC, kilativ-dotcom commented on cxx/common-module/CMakeLists.txt
> +add_library(common SHARED ${SOURCES} ${HEADERS})
common is not the best name for a module, it is very high probability that other project already has module with this name, maybe some common-ps-lib?

2024-04-13 07:32 UTC, kilativ-dotcom commented on cxx/CMakeLists.txt
> +set(NON_ATOMIC_ACTION_INTERPRETER_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/non-atomic-action-interpeter-module)
```suggestion
set(NON_ATOMIC_ACTION_INTERPRETER_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/non-atomic-action-interpreter-module)
```

2024-04-13 07:32 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/interpreter/NonAtomicActionInterpreter.cpp
> +
```suggestion
```

2024-04-13 07:32 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/test/tests.cmake
> +    INCLUDES ${SC_MEMORY_SRC}/tests/sc-memory/_test ${NON_ATOMIC_ACTION_INTERPRETER_MODULE_PATH} ${SC_MACHINE_PATH}/sc-tools/sc-builder/src)
```suggestion
    INCLUDES ${SC_MEMORY_SRC}/tests/sc-memory/_test ${NON_ATOMIC_ACTION_INTERPRETER_MODULE_PATH} ${SC_MACHINE_ROOT}/sc-tools/sc-builder/src)
```
sc-machine puts its location in SC_MACHINE_ROOT

2024-04-13 07:32 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/test/tests.cmake
> +    DEPENDS non_atomic_action_interpreter_test_agents sc-builder-lib sc-core
```suggestion
    DEPENDS non_atomic_action_interpreter_test_agents sc-builder-lib
```
this one is not required

2024-04-13 07:32 UTC, kilativ-dotcom commented on docker-compose.yml
> +
add newline

2024-04-13 07:32 UTC, kilativ-dotcom commented on mkdocs.yml
> +
add newline

2024-04-14 05:21 UTC, ProtasSemyon commented on cxx/non-atomic-action-interpreter-module/test/tests.cmake
> +    DEPENDS non_atomic_action_interpreter_test_agents sc-builder-lib sc-core
Linker error
[build] /usr/bin/ld: platform-dependent-components/problem-solver/reusable-components/cxx/non-atomic-action-interpreter-module/CMakeFiles/non_atomic_action_interpreter_test_starter.dir/test/units/testNonAtomicActionInterpreterAgent.cpp.o: undefined reference to symbol 'sc_memory_params_clear'
[build] /usr/bin/ld: /home/smn/ostis/ostis-metasystem/build/../bin/libsc-core.so: error adding symbols: DSO missing from command line

The metasystem does not include sc-machine, only its modules, it only works with this dependency.

2024-04-15 11:41 UTC, kilativ-dotcom commented on cxx/non-atomic-action-interpreter-module/interpreter/NonAtomicActionInterpreter.cpp
> +  ScAddr decompositionTuple =
https://github.com/ostis-ai/ostis-ps-lib/pull/2/files#diff-0cfbb40a87784792027f5d98ea6bf0a567217ee546989520446a3490d1c45c49
this relation goes from tuple inside non-atomic action
getAnyByInRelation was correct

2024-04-25 12:25 UTC, kilativ-dotcom commented
looks like it should work :relieved:

2024-06-11 07:47 UTC, MksmOrlov commented
No need to merge, use branches

2024-06-11 07:47 UTC, closed without merging