fix: make translators answers better
ostis-ai/ostis-ps-lib pull request #5
Opened 2024-07-10 13:36 UTC by RybakovaIE

2024-07-11 10:43 UTC, MksmOrlov requested changes

2024-07-11 10:43 UTC, MksmOrlov commented on cxx/naturalLanguageProcessingModule/translator/NodeDefinitionTranslator.cpp
> +}  // namespace naturalLanguageProcessingModule
Add newline. Check all files in your PR please

2024-07-11 10:43 UTC, MksmOrlov commented on cxx/naturalLanguageProcessingModule/translator/NodeDefinitionTranslator.cpp
> +std::vector<std::string> NodeDefinitionTranslator::getSemanticNeighbourhoods(
It looks like outdated version. 
Ты переписывала трансляторы, чтобы они возвращали stringstream, а не std::vector<std::string>. В целом, выглядит подозрительно, что папка называется не "structureTranslationModule", как в основной ветке. Может попробуй git rebase origin/feature/add_nlp_translators и вносить изменения в нужное место

2024-07-11 11:09 UTC, RybakovaIE commented on cxx/naturalLanguageProcessingModule/translator/NodeDefinitionTranslator.cpp
> +std::vector<std::string> NodeDefinitionTranslator::getSemanticNeighbourhoods(
This is another agent, that searches for semantic neighbourhoods of one node, when there is question "what is ...?"

2024-08-12 09:29 UTC, closed without merging

2024-08-12 09:29 UTC, RybakovaIE commented
https://github.com/ostis-ai/ostis-ps-lib/pull/6